name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_CONTAINER_REGISTRY_GITHUB }}

    - name: Build Docker image
      run: docker build . -t ghcr.io/my-node-app:latest

    - name: Push Docker image
      run: docker push ghcr.io/my-node-app:latest
